### PR TITLE
Linter css

### PR DESCRIPTION
**Pull request by Vidmapps**
I am not sure about parts of `0px` and color codes. As for the color codes, I guess the palet is blocking the error explanation. 
image

### CODE REVIEW

**Comment by alynioke** [comment]
What do you mean when you talk about "part with `0px` ? could you give more context please? is it an error or ?

**Comment by Vidmapps** [comment]
Unexpected unit (length-zero-no-unit)

image

**Comment by alynioke** [comment]
What i usually do, i google error code - in this case `length-zero-no-unit`. It leads to https://stylelint.io/user-guide/rules/length-zero-no-unit in this case. 
tl;dr: where there's `0px` don't use `px`. Make it just `0`

**Comment by alynioke** [comment]
And about color, error code i saw in my editor is `color-hex-case`. I believe you can find out what it means and how to fix ;) 
for future, you can:
1) disable this color palette plugin
2) use command `npx stylelint style.css` command and see all errors and codes abotu this file - same way  yo did with eslint.
image

**Pull request merged**
