### PR TITLE
Latest commits structure

### PR DESCRIPTION
**Pull request by Vidmapps**
- Added the content for `Latest commits` and `Average Operation Time`
image

- Then I decided to fix the responsiveness for the tabs making their width into the percentage form. I am not sure if I did it right, I guess we will need to have talk about the best option in these cases.

- Fixed some bugs that appeared on the process when fixing responsiveness.

I hope this PR isn't that messy... It is hard to do changes strictly per tab, I always notice some things to fix on the go in other parts. Thanks!

### CODE REVIEW

**Comment by alynioke** [comment]
choose which block Latest Commits or Average Operation Time you want to take all remaining space, and use ` flex-grow: 1`  on it!

**Comment by alynioke** [comment]
also, i think it will look better if text is vertically centered here https://monosnap.com/file/kRFxfoFTWGcPEb3jRBicTypRqH9KLu

**Comment by alynioke** [comment]
other than that all looks good 👍 let me know if you will fix my notes or no.

**Comment by Vidmapps** [comment]
Maybe you are right, just followed the given design 🤔 

image

**Comment by alynioke** [comment]
since you're trying pixel perfect it's OK to stay close to design as possible. I just couldn't check design - have no access - so wrote it as possible improvement, as centered looks better imo :) feel free to leave as your want

**Pull request merged**
